name: Build Android APK

on:
  push:
    branches: [ "main", "master" ] # يعمل عند أي تعديل
  workflow_dispatch: # يسمح لك بتشغيله بضغطة زر يدوياً

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # إعداد الجافا
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # إعداد فلاتر
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # تحميل المكاتب
      - name: Get Dependencies
        run: flutter pub get

      # بناء ملف APK
      - name: Build APK
        run: flutter build apk --release

      # رفع الملف الناتج لتقوم أنت بتنزيله
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-app-release
          path: build/app/outputs/flutter-apk/app-release.apk
